git: 
  depth: 10

language: objective-c

before_script:
  # brew
  - brew update > /dev/null
  - brew install ant pandoc > /dev/null
  - brew cask install flash-player-debugger
  # air
  - mkdir -p air_sdk
  - wget -O AIRSDK_Compiler.tbz2 https://airdownload.adobe.com/air/mac/download/latest/AIRSDK_Compiler.tbz2
  - tar -xjf AIRSDK_Compiler.tbz2 -C air_sdk
  - mkdir -p air_sdk/frameworks/libs/player/11.1/
  - wget -O playerglobal.swc https://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal19_0.swc
  - cp -f playerglobal.swc air_sdk/frameworks/libs/player/11.1/
  - export AIR_HOME="$TRAVIS_BUILD_DIR/air_sdk"
  # starling
  - git clone -b master git://github.com/Gamua/Starling-Framework.git --depth 1
  - mkdir -p third-party/starling
  - cp -r Starling-Framework/starling/src/* third-party/starling
  # flexunit
  - wget -O flexunit.zip http://mirrors.ibiblio.org/apache/flex/flexunit/4.2.0/binaries/apache-flex-flexunit-4.2.0-4.12.0-bin.zip
  - unzip -q flexunit.zip
  - mkdir -p third-party/flexunit
  - cp flexunit/* third-party/flexunit/

script:
  - ant full -Dflashsdk.root="$AIR_HOME" -Dflashplayer="/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger" -Dpandoc="/usr/local/bin/pandoc"